# Generated by Django 6.0.3 on 2026-03-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_edition_total_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='edition_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
