# Generated by Django 6.0.3 on 2026-03-13 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_article_edition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelayout',
            name='layout_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
