# Generated by Django 6.0.3 on 2026-03-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_pagelayout_layout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='received_from_edition',
            field=models.BooleanField(default=False),
        ),
    ]
